### ISSUE TITLE
CAH Creator broken

### ISSUE THREAD

**Issue by tjhorner** [juju2143/CardsAgainstEquestria#6]
**EN**: I've been getting many reports from your users that CAH Creator isn't working with this site. CAH Creator has been updated and the original Cards Against Equestria codebase has been updated as well to reflect the changes. I'm going to make a pull request to fix this and make it the same as the original game, keep an eye out for that!

**FR (Google Translate)**: Je reçois de nombreux rapports de vos utilisateurs que CAH Creator ne fonctionne pas avec ce site. CAH Creator a été mis à jour et les cartes originales contre Equestria codebase a été mis à jour et pour refléter les changements. Je vais faire une demande de tirage pour résoudre ce problème et faire la même chose que le jeu original, garder un œil sur ça!

**Comment by juju2143** [comment]
Thanks for the heads up! I'll update the codebase when I'll have some time. A pull request would also be welcome.

**Comment by tjhorner** [comment]
No problem! :smile:

It would probably be easier to send over a PR from my own fork of _this project_ since GitHub has no idea how to merge Rylius's code with yours.

**Comment by tjhorner** [comment]
PR created: #7

**Comment by juju2143** [comment]
Yeah, GitHub must be confused with all my translations and the different decks (that's the point of my fork, it's not my goal to be able to merge back into his code until he adds some sort of multilanguage feature), so I just manually merge Rylius' code into mine all the time, which is a bit tedious at times.

Anyway, I merged the PR which is supposed to fix this issue and sent it into production, so I'm going to close this issue. Again, thanks!

**Comment by tjhorner** [comment]
`cae.js` hasn't been updated to reflect the changes. Did you do `grunt` yet?

**Comment by juju2143** [comment]
Now I did.

**Comment by tjhorner** [comment]
Great! Works perfectly now.

**Comment by juju2143** [comment]
Awesome.
